#Configuracion
#Mon Jun 08 02:58:42 MST 2026
registration.window.height=784
registration.window.width=1382
registration.window.x=-8
registration.window.y=-8
ui.theme=dark
users.export.pdf=C\:\\Users\\azari\\OneDrive\\Desktop
