#Configuracion
#Thu Jun 04 14:02:19 MST 2026
registration.image.last.directory=C\:\\Users\\DASC\\Desktop
registration.window.height=597
registration.window.width=1195
registration.window.x=193
registration.window.y=132
ui.theme=dark
users.export.pdf=C\:\\Users\\azari\\OneDrive\\Desktop\\Base de Datos
uz\#Configuracion=
