#Configuracion
#Sat May 16 23:32:26 MST 2026
registration.image.last.directory=C\:\\Users\\DASC\\Desktop
registration.window.height=655
registration.window.width=1192
registration.window.x=2039
registration.window.y=77
ui.theme=dark
users.export.pdf=C\:\\Users\\azari\\OneDrive\\Desktop\\Base de Datos
uz\#Configuracion=
